import { InventoryItem } from '../types/inventory.types';

export const INVENTORY: InventoryItem[] = [
  // ── Raw Materials ──────────────────────────────────────────
  {
    id: 'inv-rm-1',
    name: 'Coffee Beans - House Blend',
    type: 'raw_material',
    stock: 5000,
    minStock: 2000,
    unit: 'gr',
    status: 'healthy',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-2',
    name: 'Fresh Milk',
    type: 'raw_material',
    stock: 2,
    minStock: 5,
    unit: 'L',
    status: 'low_stock',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-3',
    name: 'Oat Milk (Raw)',
    type: 'raw_material',
    stock: 0,
    minStock: 3,
    unit: 'L',
    status: 'out_of_stock',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-4',
    name: 'Matcha Powder',
    type: 'raw_material',
    stock: 100,
    minStock: 500,
    unit: 'gr',
    status: 'low_stock',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-5',
    name: 'Caramel Syrup',
    type: 'raw_material',
    stock: 800,
    minStock: 500,
    unit: 'ml',
    status: 'healthy',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-6',
    name: 'Chocolate Powder',
    type: 'raw_material',
    stock: 350,
    minStock: 300,
    unit: 'gr',
    status: 'healthy',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-7',
    name: 'Lychee Syrup',
    type: 'raw_material',
    stock: 450,
    minStock: 300,
    unit: 'ml',
    status: 'healthy',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-8',
    name: 'Lemon Juice',
    type: 'raw_material',
    stock: 80,
    minStock: 200,
    unit: 'ml',
    status: 'low_stock',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-9',
    name: 'Black Tea Leaves',
    type: 'raw_material',
    stock: 600,
    minStock: 300,
    unit: 'gr',
    status: 'healthy',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-10',
    name: 'Espresso Shot',
    type: 'raw_material',
    stock: 120,
    minStock: 50,
    unit: 'shot',
    status: 'healthy',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-rm-11',
    name: 'Almond (Topping)',
    type: 'raw_material',
    stock: 0,
    minStock: 200,
    unit: 'gr',
    status: 'out_of_stock',
    lastUpdated: new Date().toISOString(),
  },

  // ── Product Menu ───────────────────────────────────────────
  // Espresso Based (c1)
  {
    id: 'inv-p1',
    productId: 'p1',
    name: 'Iced Americano',
    type: 'product',
    stock: 50,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-1', materialName: 'Coffee Beans - House Blend', amountPerUnit: 18, unit: 'gr' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-p2',
    productId: 'p2',
    name: 'Caffe Latte',
    type: 'product',
    stock: 40,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-1', materialName: 'Coffee Beans - House Blend', amountPerUnit: 18, unit: 'gr' },
      { materialId: 'inv-rm-2', materialName: 'Fresh Milk', amountPerUnit: 0.15, unit: 'L' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-p3',
    productId: 'p3',
    name: 'Cappuccino',
    type: 'product',
    stock: 35,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-1', materialName: 'Coffee Beans - House Blend', amountPerUnit: 18, unit: 'gr' },
      { materialId: 'inv-rm-2', materialName: 'Fresh Milk', amountPerUnit: 0.1, unit: 'L' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-p4',
    productId: 'p4',
    name: 'Caramel Macchiato',
    type: 'product',
    stock: 30,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-1', materialName: 'Coffee Beans - House Blend', amountPerUnit: 18, unit: 'gr' },
      { materialId: 'inv-rm-2', materialName: 'Fresh Milk', amountPerUnit: 0.12, unit: 'L' },
      { materialId: 'inv-rm-5', materialName: 'Caramel Syrup', amountPerUnit: 20, unit: 'ml' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  // Non Coffee (c2)
  {
    id: 'inv-p5',
    productId: 'p5',
    name: 'Matcha Latte',
    type: 'product',
    stock: 20,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-4', materialName: 'Matcha Powder', amountPerUnit: 5, unit: 'gr' },
      { materialId: 'inv-rm-2', materialName: 'Fresh Milk', amountPerUnit: 0.15, unit: 'L' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-p6',
    productId: 'p6',
    name: 'Chocolate',
    type: 'product',
    stock: 25,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-6', materialName: 'Chocolate Powder', amountPerUnit: 20, unit: 'gr' },
      { materialId: 'inv-rm-2', materialName: 'Fresh Milk', amountPerUnit: 0.15, unit: 'L' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  // Tea (c3)
  {
    id: 'inv-p7',
    productId: 'p7',
    name: 'Lychee Tea',
    type: 'product',
    stock: 30,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-9', materialName: 'Black Tea Leaves', amountPerUnit: 5, unit: 'gr' },
      { materialId: 'inv-rm-7', materialName: 'Lychee Syrup', amountPerUnit: 30, unit: 'ml' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-p8',
    productId: 'p8',
    name: 'Lemon Tea',
    type: 'product',
    stock: 5,
    minStock: 10,
    unit: 'pcs',
    status: 'low_stock',
    requiredMaterials: [
      { materialId: 'inv-rm-9', materialName: 'Black Tea Leaves', amountPerUnit: 5, unit: 'gr' },
      { materialId: 'inv-rm-8', materialName: 'Lemon Juice', amountPerUnit: 25, unit: 'ml' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  // Pastry (c4)
  {
    id: 'inv-p9',
    productId: 'p9',
    name: 'Butter Croissant',
    type: 'product',
    stock: 15,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-p10',
    productId: 'p10',
    name: 'Almond Croissant',
    type: 'product',
    stock: 2,
    minStock: 5,
    unit: 'pcs',
    status: 'low_stock',
    requiredMaterials: [
      { materialId: 'inv-rm-11', materialName: 'Almond (Topping)', amountPerUnit: 15, unit: 'gr' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  // Add-ons (c5)
  {
    id: 'inv-p11',
    productId: 'p11',
    name: 'Extra Shot Espresso',
    type: 'product',
    stock: 999,
    minStock: 10,
    unit: 'pcs',
    status: 'healthy',
    requiredMaterials: [
      { materialId: 'inv-rm-10', materialName: 'Espresso Shot', amountPerUnit: 1, unit: 'shot' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'inv-p12',
    productId: 'p12',
    name: 'Oat Milk',
    type: 'product',
    stock: 0,
    minStock: 5,
    unit: 'pcs',
    status: 'out_of_stock',
    requiredMaterials: [
      { materialId: 'inv-rm-3', materialName: 'Oat Milk (Raw)', amountPerUnit: 0.15, unit: 'L' },
    ],
    lastUpdated: new Date().toISOString(),
  },
];
